"""Remove commission and simplify business model

Revision ID: ba2210ad5edb
Revises: 3182c63f0e76
Create Date: 2026-01-06 09:53:54.171729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2210ad5edb'
down_revision = '3182c63f0e76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commission_ledger')
    op.drop_table('wallet')
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), nullable=False))
        batch_op.drop_column('phone_number')

    op.create_table('wallet',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('balance', sa.FLOAT(), nullable=True),
    sa.Column('business_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commission_ledger',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('wallet_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
